# Introduction

&copy; 2026 by [Damir Cavar](https://damir.cavar.me/)

The following notes are supplemental material to the IBM course "[Basics of quantum information](https://quantum.cloud.ibm.com/learning/en/courses/basics-of-quantum-information/)." 


In [1]:
import numpy as np

In [2]:
Sigma = {0, 1}

$P(X = 0) = \frac{3}{4}$

$P(X = 1) = \frac{1}{4}$

$$
\begin{pmatrix}
    \frac{3}{4} \\
    \frac{1}{4}
\end{pmatrix}
$$

In [3]:
column_vector = np.array([ [3/4], [1/4] ])
print(column_vector)

[[0.75]
 [0.25]]


In numpy the sum of each column is specified using axis-0, i.e., telling the sum-function to sum down the first axis, i.e., the columns in a 2D array:

In [4]:
column_sum = np.sum(column_vector, axis=0)
print(column_sum)

[1.]


## Dirac notation

$\ket{a}$ is the column vector with a $1$ in the entry correcponding to $a \in \Sigma$, with $0$ for all other entries. If $\Sigma = \{0,1\}$:

$\ket{0}=\begin{pmatrix} 1 \\ 0 \end{pmatrix}$

and

$\ket{1}=\begin{pmatrix} 0 \\ 1 \end{pmatrix}$

These are **standard basis vectors**.

Every vector can be expressed uniquely as a linear combination of stadard basis vectors.

$$
\begin{pmatrix}
\frac{3}{4} \\
\frac{1}{4}
\end{pmatrix} = \frac{3}{4}\ket{0} + \frac{1}{4}\ket{1} = \frac{3}{4}\begin{pmatrix} 1 \\ 0 \end{pmatrix} + \frac{1}{4}\begin{pmatrix} 0 \\ 1 \end{pmatrix} = \begin{pmatrix} \frac{3}{4} \\ 0 \end{pmatrix} + \begin{pmatrix} 0 \\ \frac{1}{4} \end{pmatrix} = \begin{pmatrix} \frac{3}{4} \\ \frac{1}{4} \end{pmatrix}
$$

## Measuring probabilistic states

## Vectors

In [24]:
bra_0 = np.array( [ [ 1, 0 ] ] )
ket_0 = np.array( [ [1], [0] ] )
bra_1 = np.array( [ [ 0, 1 ] ] )
ket_1 = np.array( [ [0], [1] ] )

Multuiplying a row vector $v$ to a column vector $u$:

In [21]:
bra_0 @ ket_0

array([[1]])

In [25]:
bra_1 @ ket_1

array([[1]])

In [26]:
bra_0 @ ket_1

array([[0]])

In [27]:
bra_1 @ ket_0

array([[0]])

Multiplying a column vector $u$ to a row vector $v$:

In [22]:
ket_0 @ bra_0

array([[1, 0],
       [0, 0]])

In [28]:
ket_1 @ bra_1

array([[0, 0],
       [0, 1]])

In [29]:
ket_0 @ bra_1

array([[0, 1],
       [0, 0]])

In [30]:
ket_1 @ bra_0

array([[0, 0],
       [1, 0]])

## Matrices


In [32]:
M_1 = np.array( [
	[1, 1],
	[0, 0]
])
M_1

array([[1, 1],
       [0, 0]])

In [33]:
M_2 = np.array( [
	[0, 1],
	[1, 0]
])
M_2

array([[0, 1],
       [1, 0]])

Not cmmutative, matrix multiplication:

In [34]:
M_1 @ M_2

array([[1, 1],
       [0, 0]])

In [35]:
M_2 @ M_1

array([[0, 0],
       [1, 1]])

## Euclidean norm

For real-valued vectors the Euclidean or $L^2$ norm is:

$$
\|x\|_2=\sqrt{x_1^2 + x_2^2 + \dots + x_n^2}
$$

For complex-valued vectors, with a complex number $z = a + bi$ the magnitude is $|x_i| = \sqrt{a^2 + b^2}$, thus it is:

$$
\|x\|_2=\sqrt{ \sum_{i=1}^{n}{|x_i|^2} }
$$


In [41]:
v = np.array( [2, 3, 6] )
norm = np.linalg.norm(v)
print(norm)

7.0


In [52]:
v = np.array( [ 4 + 0j, 2 + 2j, 2 - 2j, 2 + 0j ] )
norm = np.linalg.norm(v)
print(norm)

6.0


## Complex Conjugate and Norm

Let $z = x + iy$ where $x,y\in \mathbb{R}$ and $i^2=-1$.

Then the complex conjugate of $z$ is $\overline{z}=x-iy.$

Compute the product $z\cdot \overline{z}$: $z\overline{z}=(x+iy)(x-iy).$

Expand using distributivity: $(x+iy)(x-iy)=x\cdot x+x\cdot (-iy)+iy\cdot x+iy\cdot (-iy).$

Thus: $=x^2-ixy+ixy-i^2y^2.$

The middle terms cancel: $-ixy+ixy=0.$

And since $i^2=-1$, we get: $-i^2y^2=-(-1)y^2=y^2.$

So the whole expression becomes: $z\overline{z}=x^2+y^2.$

See Figure 1 (taken from [Corinne A. Manogue and Tevian Dray "The Geometry of Linear Algebra"](https://books.physics.oregonstate.edu/LinAlg/conjugate.html#:~:text=The%20complex%20conjugate%20z%E2%88%97,1.))

![Figure 1 - Complex Conjugate of a Complex Number](cbar.png "Figure 1 - Complex Conjugate of a Complex Number")
