# Quantum Computation Primer for QC Intro 2

&copy; 2024 by [Damir Cavar](http://damir.cavar.me/)

**Sources:**

- [Quantum Computation Primer - Part 2](https://www.codeproject.com/Articles/5160469/Quantum-Computation-Primer-Part-2)

Focusing on Quantum Gates.

Implementation of algorithms:

- as a Quantum Circuit consisting of input and output qubits with gates altering the quantum states of the qubits
- one-qubit gates and multi-qubit gates
- when a qubit is measured its state collapses to one of the basis states $|0\rangle$ or $|1\rangle$
- the collapsed qubit could be thought of as a classical bit

![Example circuit](./CircuitExample.png)

Representation of Quantum Gates:

- Unitary Matrix
- A matrix is unitary if its conjugate transpose is also its inverse: $U^\intercal U = I$ that is: multiply a unitary matrix by its conjugate transpose results the identity matrix

$I_3 = \begin{bmatrix}
    1 & 0 & 0 \\ 
    0 & 1 & 0 \\
    0 & 0 & 1 
 \end{bmatrix}
 $

The subscript *3* denotes the dimensionality of the matrix.

Multiplying matices by their invers results in an identity matrix.

**Important feature:**

Multiplying a matrix by a unitary matrix preserves the norm.

That is:

- when a unitary matrix is applied to a quantum state, the sum of the probabilities remains equal to 1
- the state stays on the surface of the Block sphere
- the norm is the length of the vector from the center of the sphere

The dimensions of the matrix representing a gate is equal to $2^n \times 2^n$, where $n$ is the number of inputs.

For quantum gates, the number of inputs always equals the number of outputs.


## Gate Reversibility

Unlike gates in classical computing, quantum gates have to be reversible.

As [Gidney (2016)](https://physics.stackexchange.com/questions/270266/why-do-quantum-gates-have-to-be-reversible) states, quantum gates must be reversible because quantum mechanics is reversible.

While classical computers are able to discard accumulated information during processing, doing so in a quantum computer would count as a measurement; collapsing the quantum state.

To maintain the consistency of a superposition, the sum of all probabilities across all states must equal 1. No information can be lost when applying a gate.

Now, because the matrices representing gates are unitary, they are reversible. If you apply a gate $U$ to a state $|\psi\rangle$, you can undo it by applying $U$'s conjugate transform, which is its inverse, as shown:

$U^\intercal U|\psi\rangle=|\psi\rangle$

If we multiply a unitary matrix by its conjugate transform, the result is the identity matrix; effectively leaving the state unchanged.

**Compare quantum gates to classical gates:**

Gates like the classical AND and OR gates aren't as easy to implement in quantum computing since they are **irreversible**.

- two inputs and only one output
- reconstructing the initial input bits from the output is not possible
- information is lost

![AND OR Gates](./AndOrGates.png)

To make these gates reversible (and implement them as Quantum AND or OR gates) we can use the Controlled Swap Gate.

Reversible classical gates, as for example the NOT gate, can be easily implemented as quantum gates. In the NOT gate no information is lost. The input can be infered from the output.

![NOT Gate](./NotGate.png)


## Measuring Qubits

So far:

- measuring a qubit state collapses the qubit's state to one of its basis states $|0\rangle$ or $|1\rangle$
- Quantum gates must be reversible

Measuring a qubit is technicall not a gate (but might be called a Measurement gate). It is an irreversible activity.

Measuring results in a classical bit, indicated by the double line:

![Measurement](./Measurement.png)


# Implementing a NOT gate with the Pauli-X gate

Matrix representation of the Pauli-X gate or NOT gate:

$X = \begin{bmatrix}
    0 & 1 \\ 
    1 & 0  
 \end{bmatrix}
 $

Flipping the basis states with the Pauli-X gate:

$X|0\rangle = \begin{bmatrix}
    0 & 1 \\ 
    1 & 0  
 \end{bmatrix}
 \begin{bmatrix}
    1 \\ 
    0   
 \end{bmatrix} =
  \begin{bmatrix}
    0 \\ 
    1   
 \end{bmatrix} = |1\rangle 
 $

$X|1\rangle = \begin{bmatrix}
    0 & 1 \\ 
    1 & 0  
 \end{bmatrix}
 \begin{bmatrix}
    0 \\ 
    1   
 \end{bmatrix} =
  \begin{bmatrix}
    1 \\ 
    0   
 \end{bmatrix} = |0\rangle 
 $

The Pauli-X gate rotates a qubit on the Bloch sphere around the x-axis by $\pi$ radians (180°).

The Pauli-X gate quantum circuit symbol is  ![PauliXGate](./PauliXGate.png)

In [1]:
import numpy as np

In [2]:
X = np.array([[0, 1], [1, 0]])
print("Matrix X:\n", X)

Matrix X:
 [[0 1]
 [1 0]]


In [3]:
B = np.array([[1], [0]])
print("Matrix B:\n", B)

Matrix B:
 [[1]
 [0]]


In [4]:
X @ B

array([[0],
       [1]])

## Hadamard Gate for a 50/50 Superposition

Given the basis states:

- $|0\rangle$
- $|1\rangle$

The goal is to transform those into one of the following states:

- $|+\rangle = \frac{|0\rangle + |1\rangle}{\sqrt{2}}$
- $|-\rangle = \frac{|0\rangle - |1\rangle}{\sqrt{2}}$

Note:

- the $+$ and $-$ correspond to the sign of the amplitude of the $|1\rangle$ state

**Hadamard Gate**

$
\frac{1}{\sqrt{2}}
\begin{bmatrix}
    1 & 1 \\ 
    1 & -1  
 \end{bmatrix}
$

Applying it to $|0\rangle$:

$H|0\rangle = \frac{1}{\sqrt{2}}
\begin{bmatrix}
    1 & 1 \\ 
    1 & -1  
 \end{bmatrix}
\begin{bmatrix}
    1  \\ 
    0   
 \end{bmatrix}
= \frac{1}{\sqrt{2}}
\begin{bmatrix}
    1  \\ 
    1   
 \end{bmatrix}
= \frac{1}{\sqrt{2}} \left(
\begin{bmatrix}
    1  \\ 
    0   
 \end{bmatrix}
 + 
 \begin{bmatrix}
    0  \\ 
    1   
 \end{bmatrix}
\right) = \frac{|0\rangle + |1\rangle}{\sqrt{2}}$

$|+\rangle$ and $|-\rangle$ are located on the equator of the Bloch sphere, halfway between $|0\rangle$ and $|1\rangle$ having a probability of 50%.

![Block Sphere H](./BlochSphereHKet0_2.png)

The circuit symbol for the Hadamard gate is: ![H Gate](./HGate.png)


Expanding the application of the Hadamard gate to $n$ qubits with $2^n$ observable states:

$\ket{\psi} = \frac{\ket{0 \ldots 000} + \ket{0 \ldots 001} + \ldots + \ket{1 \ldots 111}}{\sqrt{2^n}}$




## Operators

An operator is a function that maps linearly from one value to another value in complex space.

Gates could be described as operators.

A function is a linear map if it preserves addition and multiplication.

$f(u+v) = f(u) + f(v)$

also:

$f(c \times u) = c \times f(u)$


## Controlled NOT Gate

Controlled-Not gate (CNOT) is analogous to the XOR gate (Exclusive OR) in classical computing.

In classical computing:

- the XOR operation takes two inputs
- if both of the inputs are 1, then the output is 0; otherwise the result is unaffected

Truth table for XOR:

$\begin{array}{ccc} A & B & A \oplus B \\ \hline 0 & 0 & 0 \\ 0 & 1 & 1 \\ 1 & 0 & 1 \\ 1 & 1 & 0 \end{array}$

Quantum Controlled NOT (CNOT) Gate:

- two inputs and two outputs
- target input is negated only if the control input is 1
- if control is 0, the result is unaffected

![CNOT Gate](./CnotGate.png)

Truth Table for the CNOT Gate:

$\begin{array}{cc|cc} \rlap{In} & & \rlap{Out} & \\ \hline Control & Target & Control & Target \\ \hline 0 & 0 & 0 & 0 \\ 0 & 1 & 0 & 1 \\ 1 & 0 & 1 & 1 \\ 1 & 1 & 1 & 0 \end{array}$

The target output column of CNOT corresponds to the $A \oplus B$ column in XOR.

- CNOT has two inputs and two outputs, thus it is a $2^{inputCount} \times 2^{outputCounts} = 4 \times 4$ matrix.

$CNOT = \begin{bmatrix} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0 \end{bmatrix}$

Examples:

$CNOT \ket{00} = \begin{bmatrix} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0 \end{bmatrix} \begin{bmatrix} 1 \\ 0 \\ 0 \\ 0 \end{bmatrix} = \begin{bmatrix} 1 \\ 0 \\ 0 \\ 0 \end{bmatrix} = \ket{00}$

$CNOT \ket{10} = \begin{bmatrix} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0 \end{bmatrix} \begin{bmatrix} 0 \\ 0 \\ 1 \\ 0 \end{bmatrix} = \begin{bmatrix} 0 \\ 0 \\ 0 \\ 1 \end{bmatrix} = \ket{11}$



## Bell States

Four different Bell States:

$\ket{\Phi^-} = \frac{\ket{00} - \ket{11}}{\sqrt{2}}$

$\ket{\Phi^-} = \frac{\ket{00} - \ket{11}}{\sqrt{2}}$

$\ket{\Psi^+} = \frac{\ket{01} + \ket{10}}{\sqrt{2}}$

$\ket{\Psi^-} = \frac{\ket{01} - \ket{10}}{\sqrt{2}}$

This is based on the four different basis states and the permutation of the $+$ or $-$ operation.

![Bell State](./HCnot.png)

